<?php
class dados { 
    public $entrada = array(
        [
            "name" => "Kasper Levine",
            "phone" => "(289) 102-9462",
            "email" => "lacus.ut@yahoo.ca",
            "address" => "166-9453 Quis Street",
            "list" => "3",
            "country" => "Australia",
            "region" => "İzmir",
            "postalZip" => "674068",
            "text" => "amet, consectetuer adipiscing elit. Aliquam auctor, velit eget laoreet posuere,",
            "numberrange" => "3",
            "currency" => "$24.17",
            "alphanumeric" => "BNL02FJU5JE"
        ],
        [
            "name" => "Harding Barron",
            "phone" => "(454) 884-6633",
            "email" => "auctor.odio@hotmail.org",
            "address" => "Ap #740-2938 Lorem Av.",
            "list" => "7",
            "country" => "Italy",
            "region" => "Maule",
            "postalZip" => "511461",
            "text" => "lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi.",
            "numberrange" => "1",
            "currency" => "$92.52",
            "alphanumeric" => "JNW27HAS8XS"
        ],
        [
            "name" => "Noelani Mercado",
            "phone" => "(419) 624-6361",
            "email" => "lacus.mauris@yahoo.com",
            "address" => "9975 Nibh Street",
            "list" => "19",
            "country" => "France",
            "region" => "Upper Austria",
            "postalZip" => "60864",
            "text" => "adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc",
            "numberrange" => "9",
            "currency" => "$13.76",
            "alphanumeric" => "WIX74XGF2RU"
        ],
        [
            "name" => "Herman Cross",
            "phone" => "(288) 238-0865",
            "email" => "egestas@hotmail.org",
            "address" => "6940 Aliquam Avenue",
            "list" => "15",
            "country" => "Ukraine",
            "region" => "New South Wales",
            "postalZip" => "578265",
            "text" => "nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor",
            "numberrange" => "9",
            "currency" => "$92.37",
            "alphanumeric" => "XNZ87CBH4KV"
        ],
        [
            "name" => "Rowan Roberts",
            "phone" => "1-574-965-3375",
            "email" => "praesent.eu.nulla@icloud.org",
            "address" => "811-6181 Lorem Road",
            "list" => "13",
            "country" => "Mexico",
            "region" => "Northern Cape",
            "postalZip" => "85-787",
            "text" => "lorem ipsum sodales purus, in molestie tortor nibh sit amet",
            "numberrange" => "7",
            "currency" => "$17.77",
            "alphanumeric" => "QPW37SFK7GW"
        ],
        [
            "name" => "Preston Clements",
            "phone" => "1-415-342-6490",
            "email" => "dolor.donec@outlook.couk",
            "address" => "Ap #897-7311 Auctor, Street",
            "list" => "1",
            "country" => "Canada",
            "region" => "South Chungcheong",
            "postalZip" => "69-143",
            "text" => "Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum",
            "numberrange" => "2",
            "currency" => "$63.70",
            "alphanumeric" => "DLQ41BDJ4IM"
        ],
        [
            "name" => "Melvin Harrington",
            "phone" => "1-674-372-5317",
            "email" => "ornare.fusce.mollis@icloud.ca",
            "address" => "890-7960 Natoque Rd.",
            "list" => "7",
            "country" => "Poland",
            "region" => "Schleswig-Holstein",
            "postalZip" => "534257",
            "text" => "Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis",
            "numberrange" => "9",
            "currency" => "$32.20",
            "alphanumeric" => "TMT23EFP4NT"
        ],
        [
            "name" => "Natalie Barnes",
            "phone" => "1-248-353-3120",
            "email" => "ante.dictum@aol.couk",
            "address" => "Ap #841-8558 Malesuada St.",
            "list" => "17",
            "country" => "Germany",
            "region" => "Imo",
            "postalZip" => "H2V 7OC",
            "text" => "in, cursus et, eros. Proin ultrices. Duis volutpat nunc sit",
            "numberrange" => "2",
            "currency" => "$91.86",
            "alphanumeric" => "XLM15KPY2FS"
        ],
        [
            "name" => "Vance Irwin",
            "phone" => "1-535-447-2687",
            "email" => "gravida.praesent@hotmail.couk",
            "address" => "660-5132 Orci. Rd.",
            "list" => "7",
            "country" => "Sweden",
            "region" => "Junín",
            "postalZip" => "770711",
            "text" => "ultricies ornare, elit elit fermentum risus, at fringilla purus mauris",
            "numberrange" => "10",
            "currency" => "$81.44",
            "alphanumeric" => "KPO92KOV2JM"
        ],
        [
            "name" => "Mason Mcmillan",
            "phone" => "(863) 368-4158",
            "email" => "tempus.eu.ligula@hotmail.ca",
            "address" => "329-5365 Enim Av.",
            "list" => "9",
            "country" => "Spain",
            "region" => "Central Luzon",
            "postalZip" => "937285",
            "text" => "non ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet,",
            "numberrange" => "3",
            "currency" => "$81.98",
            "alphanumeric" => "ESB41LRR6MF"
        ],
        [
            "name" => "Fuller Freeman",
            "phone" => "1-843-157-6081",
            "email" => "cursus.diam@yahoo.net",
            "address" => "2262 Dolor Av.",
            "list" => "17",
            "country" => "Belgium",
            "region" => "Punjab",
            "postalZip" => "775537",
            "text" => "fermentum metus. Aenean sed pede nec ante blandit viverra. Donec",
            "numberrange" => "4",
            "currency" => "$52.78",
            "alphanumeric" => "RHU05AKH8RW"
        ],
        [
            "name" => "Devin Jenkins",
            "phone" => "(287) 725-0981",
            "email" => "tristique.pharetra.quisque@google.org",
            "address" => "Ap #208-1292 Ultricies Rd.",
            "list" => "11",
            "country" => "France",
            "region" => "Nordland",
            "postalZip" => "14511",
            "text" => "mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet,",
            "numberrange" => "3",
            "currency" => "$67.90",
            "alphanumeric" => "DJI48THF2RR"
        ],
        [
            "name" => "Porter Gaines",
            "phone" => "(563) 868-1122",
            "email" => "lectus.justo@protonmail.com",
            "address" => "301-1225 Nibh. Av.",
            "list" => "5",
            "country" => "Pakistan",
            "region" => "Kerala",
            "postalZip" => "1427",
            "text" => "dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate",
            "numberrange" => "6",
            "currency" => "$90.70",
            "alphanumeric" => "KJB14SSF5QY"
        ],
        [
            "name" => "Rudyard Hammond",
            "phone" => "1-513-705-1263",
            "email" => "ipsum.primis@protonmail.org",
            "address" => "Ap #474-2634 Nec Rd.",
            "list" => "7",
            "country" => "Turkey",
            "region" => "Nghệ An",
            "postalZip" => "44786-71035",
            "text" => "auctor odio a purus. Duis elementum, dui quis accumsan convallis,",
            "numberrange" => "9",
            "currency" => "$30.52",
            "alphanumeric" => "NYI18HPW4LN"
        ],
        [
            "name" => "Maite Frederick",
            "phone" => "(334) 882-9788",
            "email" => "amet.lorem.semper@protonmail.net",
            "address" => "782-8125 Pharetra St.",
            "list" => "1",
            "country" => "Brazil",
            "region" => "Andaman and Nicobar Islands",
            "postalZip" => "3851",
            "text" => "urna, nec luctus felis purus ac tellus. Suspendisse sed dolor.",
            "numberrange" => "4",
            "currency" => "$73.61",
            "alphanumeric" => "LDV87GYR3PL"
        ],
        [
            "name" => "Brynn Holloway",
            "phone" => "1-577-781-6225",
            "email" => "nonummy@hotmail.com",
            "address" => "4532 Fermentum Rd.",
            "list" => "7",
            "country" => "South Korea",
            "region" => "Balıkesir",
            "postalZip" => "5090",
            "text" => "mus. Donec dignissim magna a tortor. Nunc commodo auctor velit.",
            "numberrange" => "5",
            "currency" => "$50.35",
            "alphanumeric" => "NAK63XWV0AF"
        ],
        [
            "name" => "Alvin Rivas",
            "phone" => "(379) 284-6657",
            "email" => "a.dui.cras@outlook.net",
            "address" => "284-6380 Magna. Ave",
            "list" => "15",
            "country" => "Colombia",
            "region" => "Queensland",
            "postalZip" => "71167",
            "text" => "Donec non justo. Proin non massa non ante bibendum ullamcorper.",
            "numberrange" => "5",
            "currency" => "$90.23",
            "alphanumeric" => "IXB34CHT3NC"
        ],
        [
            "name" => "Russell Johnson",
            "phone" => "(457) 214-6653",
            "email" => "vitae@hotmail.org",
            "address" => "P.O. Box 538, 2746 Congue St.",
            "list" => "15",
            "country" => "Poland",
            "region" => "North Island",
            "postalZip" => "8845 ZA",
            "text" => "montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque",
            "numberrange" => "9",
            "currency" => "$33.21",
            "alphanumeric" => "WTB77RBY8WR"
        ],
        [
            "name" => "Tallulah Navarro",
            "phone" => "(276) 652-5932",
            "email" => "interdum.feugiat.sed@protonmail.couk",
            "address" => "Ap #131-9415 Consequat Rd.",
            "list" => "13",
            "country" => "Belgium",
            "region" => "Zhōngnán",
            "postalZip" => "37222",
            "text" => "mattis semper, dui lectus rutrum urna, nec luctus felis purus",
            "numberrange" => "5",
            "currency" => "$38.67",
            "alphanumeric" => "IFF64DII3IP"
        ],
        [
            "name" => "Benjamin Simon",
            "phone" => "(276) 646-8340",
            "email" => "maecenas.libero@hotmail.net",
            "address" => "124-4510 Amet Street",
            "list" => "19",
            "country" => "Nigeria",
            "region" => "Kocaeli",
            "postalZip" => "04466",
            "text" => "in consequat enim diam vel arcu. Curabitur ut odio vel",
            "numberrange" => "8",
            "currency" => "$98.52",
            "alphanumeric" => "VLI58XQX2WE"
        ],
        [
            "name" => "Amaya Santana",
            "phone" => "(372) 780-0590",
            "email" => "aliquam.nec@aol.com",
            "address" => "7186 Interdum Ave",
            "list" => "9",
            "country" => "Nigeria",
            "region" => "Mpumalanga",
            "postalZip" => "9876",
            "text" => "erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla",
            "numberrange" => "1",
            "currency" => "$54.66",
            "alphanumeric" => "QQC51SYH5OZ"
        ],
        [
            "name" => "Francis Ryan",
            "phone" => "(687) 726-7148",
            "email" => "arcu.sed.eu@yahoo.couk",
            "address" => "166-2120 Ante, St.",
            "list" => "19",
            "country" => "Sweden",
            "region" => "Oyo",
            "postalZip" => "9325-2889",
            "text" => "magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl.",
            "numberrange" => "4",
            "currency" => "$33.19",
            "alphanumeric" => "CGZ33KFN8GE"
        ],
        [
            "name" => "Mark Santos",
            "phone" => "(842) 271-6928",
            "email" => "quisque.purus@hotmail.org",
            "address" => "Ap #533-2445 Ut, St.",
            "list" => "1",
            "country" => "Colombia",
            "region" => "Maine",
            "postalZip" => "4567",
            "text" => "Praesent eu nulla at sem molestie sodales. Mauris blandit enim",
            "numberrange" => "5",
            "currency" => "$80.94",
            "alphanumeric" => "ZQW88GQO4FW"
        ],
        [
            "name" => "MacKenzie Salazar",
            "phone" => "(248) 481-8693",
            "email" => "duis.sit@google.edu",
            "address" => "Ap #125-9931 Ipsum Rd.",
            "list" => "11",
            "country" => "Chile",
            "region" => "Luhansk oblast",
            "postalZip" => "3633",
            "text" => "dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque",
            "numberrange" => "5",
            "currency" => "$11.97",
            "alphanumeric" => "EMZ47QJY8TZ"
        ],
        [
            "name" => "Deanna Powers",
            "phone" => "(748) 486-6813",
            "email" => "ac.urna@outlook.edu",
            "address" => "P.O. Box 538, 6582 Sociosqu Rd.",
            "list" => "5",
            "country" => "Netherlands",
            "region" => "Gävleborgs län",
            "postalZip" => "574896",
            "text" => "Cras sed leo. Cras vehicula aliquet libero. Integer in magna.",
            "numberrange" => "3",
            "currency" => "$61.73",
            "alphanumeric" => "BHD73DUF7GT"
        ],
        [
            "name" => "Hedley Robertson",
            "phone" => "(343) 242-2170",
            "email" => "interdum.curabitur@protonmail.net",
            "address" => "1164 Etiam Road",
            "list" => "1",
            "country" => "Costa Rica",
            "region" => "New South Wales",
            "postalZip" => "43671",
            "text" => "mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida",
            "numberrange" => "8",
            "currency" => "$69.64",
            "alphanumeric" => "JGJ84MHL8TC"
        ],
        [
            "name" => "Cara Melton",
            "phone" => "(861) 677-2815",
            "email" => "mauris.ipsum.porta@hotmail.org",
            "address" => "143-4627 Suspendisse St.",
            "list" => "15",
            "country" => "Poland",
            "region" => "Kocaeli",
            "postalZip" => "91-762",
            "text" => "auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi",
            "numberrange" => "3",
            "currency" => "$4.07",
            "alphanumeric" => "BKI36IWV4YI"
        ],
        [
            "name" => "Rebekah Barr",
            "phone" => "1-646-450-2778",
            "email" => "amet@hotmail.org",
            "address" => "781-1509 Velit. Avenue",
            "list" => "9",
            "country" => "Pakistan",
            "region" => "Carinthia",
            "postalZip" => "922666",
            "text" => "ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu",
            "numberrange" => "8",
            "currency" => "$63.20",
            "alphanumeric" => "EZH53MVW4NI"
        ],
        [
            "name" => "Nelle Hale",
            "phone" => "1-271-885-1604",
            "email" => "in.faucibus@hotmail.edu",
            "address" => "6199 Sem Street",
            "list" => "15",
            "country" => "Pakistan",
            "region" => "Monmouthshire",
            "postalZip" => "78-54",
            "text" => "luctus sit amet, faucibus ut, nulla. Cras eu tellus eu",
            "numberrange" => "4",
            "currency" => "$45.98",
            "alphanumeric" => "EPB92WXS8XP"
        ],
        [
            "name" => "Allistair Clayton",
            "phone" => "1-281-193-2214",
            "email" => "quisque.ornare.tortor@icloud.org",
            "address" => "P.O. Box 509, 4881 Lobortis Rd.",
            "list" => "1",
            "country" => "Spain",
            "region" => "Wielkopolskie",
            "postalZip" => "36675",
            "text" => "ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor",
            "numberrange" => "8",
            "currency" => "$32.91",
            "alphanumeric" => "NTP54SWY7EK"
        ],
        [
            "name" => "Harding Molina",
            "phone" => "(818) 511-3538",
            "email" => "lorem.semper@outlook.couk",
            "address" => "442-5502 Urna. Rd.",
            "list" => "7",
            "country" => "Australia",
            "region" => "Viken",
            "postalZip" => "959423",
            "text" => "vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim.",
            "numberrange" => "6",
            "currency" => "$15.76",
            "alphanumeric" => "EKA87SWC3ES"
        ],
        [
            "name" => "Donna Irwin",
            "phone" => "1-818-459-3112",
            "email" => "adipiscing@protonmail.couk",
            "address" => "9246 Porttitor St.",
            "list" => "13",
            "country" => "Pakistan",
            "region" => "South Island",
            "postalZip" => "1778",
            "text" => "volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat",
            "numberrange" => "9",
            "currency" => "$38.16",
            "alphanumeric" => "YKN89MWK8SR"
        ],
        [
            "name" => "Wilma Barber",
            "phone" => "(494) 863-3773",
            "email" => "amet.faucibus@yahoo.net",
            "address" => "241-6414 Et, Rd.",
            "list" => "3",
            "country" => "Indonesia",
            "region" => "North-East Region",
            "postalZip" => "J4T 3Y4",
            "text" => "egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor",
            "numberrange" => "4",
            "currency" => "$9.12",
            "alphanumeric" => "JIT36STG8EB"
        ],
        [
            "name" => "Claire Houston",
            "phone" => "1-177-342-3714",
            "email" => "nullam.suscipit@protonmail.couk",
            "address" => "P.O. Box 391, 1329 Lacus Street",
            "list" => "7",
            "country" => "South Africa",
            "region" => "Burgenland",
            "postalZip" => "58299",
            "text" => "ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo",
            "numberrange" => "8",
            "currency" => "$58.18",
            "alphanumeric" => "IKL15NSF7UR"
        ],
        [
            "name" => "Dolan Wagner",
            "phone" => "(771) 248-7613",
            "email" => "et@google.edu",
            "address" => "Ap #151-8226 Vitae Road",
            "list" => "3",
            "country" => "Poland",
            "region" => "Eastern Cape",
            "postalZip" => "902384",
            "text" => "mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam",
            "numberrange" => "10",
            "currency" => "$46.37",
            "alphanumeric" => "QPO19ILO3WC"
        ],
        [
            "name" => "Vaughan Mcguire",
            "phone" => "(806) 500-4183",
            "email" => "mi.fringilla@protonmail.edu",
            "address" => "4537 Est Av.",
            "list" => "9",
            "country" => "Austria",
            "region" => "Northern Cape",
            "postalZip" => "93394",
            "text" => "et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim",
            "numberrange" => "4",
            "currency" => "$4.23",
            "alphanumeric" => "NIP96OVZ1YV"
        ],
        [
            "name" => "Cassandra Anthony",
            "phone" => "1-681-545-4287",
            "email" => "dolor.quam@protonmail.couk",
            "address" => "7762 In Street",
            "list" => "11",
            "country" => "Costa Rica",
            "region" => "Arunachal Pradesh",
            "postalZip" => "538131",
            "text" => "faucibus id, libero. Donec consectetuer mauris id sapien. Cras dolor",
            "numberrange" => "8",
            "currency" => "$77.55",
            "alphanumeric" => "EAK43RFK7JL"
        ],
        [
            "name" => "Jameson Gibbs",
            "phone" => "1-659-634-9654",
            "email" => "enim.suspendisse@protonmail.edu",
            "address" => "Ap #364-2236 Ipsum. Road",
            "list" => "15",
            "country" => "United States",
            "region" => "Brussels Hoofdstedelijk Gewest",
            "postalZip" => "38377",
            "text" => "eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus",
            "numberrange" => "9",
            "currency" => "$23.18",
            "alphanumeric" => "SGE24KKS2RC"
        ],
        [
            "name" => "Whitney Richardson",
            "phone" => "1-384-341-1173",
            "email" => "cubilia.curae.phasellus@aol.net",
            "address" => "Ap #323-9677 Laoreet, St.",
            "list" => "13",
            "country" => "South Korea",
            "region" => "Vlaams-Brabant",
            "postalZip" => "4677",
            "text" => "mollis lectus pede et risus. Quisque libero lacus, varius et,",
            "numberrange" => "2",
            "currency" => "$41.95",
            "alphanumeric" => "WEH16UCQ8BF"
        ],
        [
            "name" => "Finn Davenport",
            "phone" => "(848) 876-4337",
            "email" => "molestie@aol.net",
            "address" => "5252 Penatibus Av.",
            "list" => "13",
            "country" => "Norway",
            "region" => "Oslo",
            "postalZip" => "704393",
            "text" => "Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor",
            "numberrange" => "5",
            "currency" => "$21.59",
            "alphanumeric" => "VEO81LJU9GT"
        ],
        [
            "name" => "Octavia Serrano",
            "phone" => "(151) 882-8616",
            "email" => "senectus.et@yahoo.couk",
            "address" => "483-4515 Maecenas Ave",
            "list" => "15",
            "country" => "Poland",
            "region" => "Van",
            "postalZip" => "4700",
            "text" => "tempus non, lacinia at, iaculis quis, pede. Praesent eu dui.",
            "numberrange" => "6",
            "currency" => "$80.96",
            "alphanumeric" => "CLW11KIG5DT"
        ],
        [
            "name" => "Brooke Hogan",
            "phone" => "(562) 434-6561",
            "email" => "phasellus.dolor@protonmail.edu",
            "address" => "584-7904 Nibh Ave",
            "list" => "19",
            "country" => "United Kingdom",
            "region" => "Bicol Region",
            "postalZip" => "34243",
            "text" => "risus quis diam luctus lobortis. Class aptent taciti sociosqu ad",
            "numberrange" => "5",
            "currency" => "$6.08",
            "alphanumeric" => "XHK91AYI1VI"
        ],
        [
            "name" => "Arsenio Stephenson",
            "phone" => "1-869-812-7877",
            "email" => "velit.dui@protonmail.org",
            "address" => "514 Aliquam Road",
            "list" => "17",
            "country" => "Pakistan",
            "region" => "Northern Territory",
            "postalZip" => "60707",
            "text" => "pretium aliquet, metus urna convallis erat, eget tincidunt dui augue",
            "numberrange" => "9",
            "currency" => "$59.36",
            "alphanumeric" => "RHM88NEI5NB"
        ],
        [
            "name" => "Patricia Barron",
            "phone" => "1-135-714-8773",
            "email" => "purus.ac@yahoo.org",
            "address" => "700-4487 Ante, Road",
            "list" => "15",
            "country" => "France",
            "region" => "Lombardia",
            "postalZip" => "237137",
            "text" => "Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus,",
            "numberrange" => "5",
            "currency" => "$23.69",
            "alphanumeric" => "TNH59QHF8JV"
        ],
        [
            "name" => "Risa Gill",
            "phone" => "1-246-664-2093",
            "email" => "vestibulum.lorem@protonmail.edu",
            "address" => "Ap #970-7958 Phasellus Rd.",
            "list" => "15",
            "country" => "Italy",
            "region" => "Luxemburg",
            "postalZip" => "685768",
            "text" => "sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id",
            "numberrange" => "5",
            "currency" => "$64.39",
            "alphanumeric" => "CGD84UYH9LI"
        ],
        [
            "name" => "Deacon Figueroa",
            "phone" => "(515) 711-2851",
            "email" => "phasellus@google.com",
            "address" => "Ap #346-4846 Maecenas Street",
            "list" => "3",
            "country" => "Netherlands",
            "region" => "Dōngběi",
            "postalZip" => "939725",
            "text" => "bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus urna",
            "numberrange" => "9",
            "currency" => "$51.55",
            "alphanumeric" => "CRU53NQV0AF"
        ],
        [
            "name" => "Kirk Cantu",
            "phone" => "(694) 366-9811",
            "email" => "aliquam@google.com",
            "address" => "257-986 A, Av.",
            "list" => "11",
            "country" => "Germany",
            "region" => "Hải Phòng",
            "postalZip" => "222455",
            "text" => "ut odio vel est tempor bibendum. Donec felis orci, adipiscing",
            "numberrange" => "4",
            "currency" => "$92.59",
            "alphanumeric" => "KIC99HDS5LO"
        ],
        [
            "name" => "Reagan Sellers",
            "phone" => "(928) 783-2029",
            "email" => "proin.non@google.com",
            "address" => "321-3507 Scelerisque Street",
            "list" => "17",
            "country" => "Colombia",
            "region" => "Alajuela",
            "postalZip" => "56061",
            "text" => "adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis",
            "numberrange" => "7",
            "currency" => "$54.86",
            "alphanumeric" => "WCW19WJB2WF"
        ],
        [
            "name" => "Guinevere Cook",
            "phone" => "(835) 526-4450",
            "email" => "donec.fringilla@yahoo.edu",
            "address" => "Ap #303-7944 Magna. Av.",
            "list" => "1",
            "country" => "France",
            "region" => "Stockholms län",
            "postalZip" => "2313",
            "text" => "commodo at, libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus",
            "numberrange" => "8",
            "currency" => "$51.04",
            "alphanumeric" => "SII14DWJ1XS"
        ],
        [
            "name" => "Freya Barker",
            "phone" => "(577) 366-9770",
            "email" => "mus@outlook.ca",
            "address" => "799-4348 Mauris, Rd.",
            "list" => "1",
            "country" => "Austria",
            "region" => "Prince Edward Island",
            "postalZip" => "58606-314",
            "text" => "fringilla cursus purus. Nullam scelerisque neque sed sem egestas blandit.",
            "numberrange" => "7",
            "currency" => "$80.25",
            "alphanumeric" => "CNT45ZVT6MF"
        ],
        [
            "name" => "Matthew Nixon",
            "phone" => "(810) 674-5043",
            "email" => "ligula.nullam@google.couk",
            "address" => "Ap #231-4901 Hendrerit Rd.",
            "list" => "15",
            "country" => "Costa Rica",
            "region" => "British Columbia",
            "postalZip" => "113094",
            "text" => "malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris",
            "numberrange" => "3",
            "currency" => "$20.31",
            "alphanumeric" => "JFD95YRI3CP"
        ],
        [
            "name" => "Kieran Cash",
            "phone" => "(779) 245-2681",
            "email" => "non.leo.vivamus@protonmail.com",
            "address" => "Ap #832-5724 Metus Av.",
            "list" => "9",
            "country" => "Singapore",
            "region" => "California",
            "postalZip" => "18598",
            "text" => "In mi pede, nonummy ut, molestie in, tempus eu, ligula.",
            "numberrange" => "4",
            "currency" => "$93.51",
            "alphanumeric" => "NJG27KBK3UT"
        ],
        [
            "name" => "Jasper Cote",
            "phone" => "(256) 144-1415",
            "email" => "lectus.quis@icloud.couk",
            "address" => "722-2376 Aliquam Road",
            "list" => "11",
            "country" => "Indonesia",
            "region" => "Oost-Vlaanderen",
            "postalZip" => "8074",
            "text" => "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices",
            "numberrange" => "5",
            "currency" => "$16.81",
            "alphanumeric" => "VYM73CGY1QC"
        ],
        [
            "name" => "Chiquita Mcguire",
            "phone" => "1-528-124-2308",
            "email" => "et.euismod@google.ca",
            "address" => "2805 Tincidunt Rd.",
            "list" => "11",
            "country" => "Vietnam",
            "region" => "North Region",
            "postalZip" => "42446",
            "text" => "vitae erat vel pede blandit congue. In scelerisque scelerisque dui.",
            "numberrange" => "6",
            "currency" => "$0.52",
            "alphanumeric" => "DIR69JOA5HF"
        ],
        [
            "name" => "Autumn Sexton",
            "phone" => "(123) 514-2326",
            "email" => "sapien.molestie@hotmail.org",
            "address" => "774-869 Lorem. St.",
            "list" => "5",
            "country" => "Canada",
            "region" => "Brussels Hoofdstedelijk Gewest",
            "postalZip" => "42161",
            "text" => "mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla",
            "numberrange" => "9",
            "currency" => "$38.90",
            "alphanumeric" => "XLK17CUY5UI"
        ],
        [
            "name" => "Ria Nash",
            "phone" => "1-591-482-6529",
            "email" => "vel.venenatis.vel@yahoo.edu",
            "address" => "Ap #565-7149 Eleifend Ave",
            "list" => "9",
            "country" => "Ireland",
            "region" => "Bicol Region",
            "postalZip" => "682445",
            "text" => "ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id",
            "numberrange" => "4",
            "currency" => "$3.53",
            "alphanumeric" => "ERY06OSY4DX"
        ],
        [
            "name" => "Nero Battle",
            "phone" => "(819) 456-2382",
            "email" => "mauris.blandit@aol.couk",
            "address" => "8850 Sed Ave",
            "list" => "19",
            "country" => "Netherlands",
            "region" => "East Region",
            "postalZip" => "521386",
            "text" => "semper. Nam tempor diam dictum sapien. Aenean massa. Integer vitae",
            "numberrange" => "6",
            "currency" => "$22.97",
            "alphanumeric" => "WWK56TYZ6GH"
        ],
        [
            "name" => "Hunter Aguilar",
            "phone" => "1-764-833-4573",
            "email" => "aliquam@yahoo.org",
            "address" => "443-3370 Sit St.",
            "list" => "11",
            "country" => "Belgium",
            "region" => "Baja California",
            "postalZip" => "0522",
            "text" => "Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci,",
            "numberrange" => "5",
            "currency" => "$91.88",
            "alphanumeric" => "KBJ79RPK8SB"
        ],
        [
            "name" => "Karleigh Noel",
            "phone" => "1-344-676-0841",
            "email" => "cras.eget@hotmail.ca",
            "address" => "944-3051 A Rd.",
            "list" => "5",
            "country" => "Poland",
            "region" => "Alajuela",
            "postalZip" => "05582",
            "text" => "lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan",
            "numberrange" => "7",
            "currency" => "$27.04",
            "alphanumeric" => "TGH69DLV6WV"
        ],
        [
            "name" => "Carla Finley",
            "phone" => "1-856-518-5091",
            "email" => "malesuada@protonmail.edu",
            "address" => "7025 Curae Rd.",
            "list" => "11",
            "country" => "Indonesia",
            "region" => "Dalarnas län",
            "postalZip" => "516673",
            "text" => "Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus.",
            "numberrange" => "8",
            "currency" => "$35.20",
            "alphanumeric" => "MTP68LVK2DG"
        ],
        [
            "name" => "Perry Spears",
            "phone" => "(785) 827-1802",
            "email" => "quis.massa@protonmail.edu",
            "address" => "996-2650 Malesuada Ave",
            "list" => "17",
            "country" => "Nigeria",
            "region" => "Punjab",
            "postalZip" => "63423",
            "text" => "Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo.",
            "numberrange" => "2",
            "currency" => "$69.78",
            "alphanumeric" => "TNL69LQW3UD"
        ],
        [
            "name" => "Karleigh Clark",
            "phone" => "(746) 475-2137",
            "email" => "euismod.ac.fermentum@aol.com",
            "address" => "905-4597 Et Rd.",
            "list" => "17",
            "country" => "Nigeria",
            "region" => "Los Ríos",
            "postalZip" => "26892",
            "text" => "sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue",
            "numberrange" => "2",
            "currency" => "$9.78",
            "alphanumeric" => "EMX13BEI5HN"
        ],
        [
            "name" => "Carson Chaney",
            "phone" => "1-665-878-1764",
            "email" => "aenean.eget@google.org",
            "address" => "9987 Nam St.",
            "list" => "3",
            "country" => "South Africa",
            "region" => "Uttarakhand",
            "postalZip" => "F7W 0L2",
            "text" => "Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra.",
            "numberrange" => "8",
            "currency" => "$29.15",
            "alphanumeric" => "GVQ75IWW7FW"
        ],
        [
            "name" => "Lester Holmes",
            "phone" => "1-529-451-6262",
            "email" => "sed.nulla@protonmail.org",
            "address" => "Ap #455-8520 Donec Road",
            "list" => "7",
            "country" => "Nigeria",
            "region" => "Hòa Bình",
            "postalZip" => "4634",
            "text" => "adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque",
            "numberrange" => "2",
            "currency" => "$9.69",
            "alphanumeric" => "OML65CUY7IP"
        ],
        [
            "name" => "Otto Sanders",
            "phone" => "1-856-114-1677",
            "email" => "consectetuer.euismod.est@google.org",
            "address" => "844-7942 Litora Street",
            "list" => "1",
            "country" => "Canada",
            "region" => "Puno",
            "postalZip" => "5181",
            "text" => "neque sed sem egestas blandit. Nam nulla magna, malesuada vel,",
            "numberrange" => "3",
            "currency" => "$71.71",
            "alphanumeric" => "NYB22OWO4XT"
        ],
        [
            "name" => "Carol Slater",
            "phone" => "1-863-684-0925",
            "email" => "cras@protonmail.net",
            "address" => "Ap #700-3176 Suspendisse Rd.",
            "list" => "5",
            "country" => "Nigeria",
            "region" => "North Kalimantan",
            "postalZip" => "33267",
            "text" => "nec enim. Nunc ut erat. Sed nunc est, mollis non,",
            "numberrange" => "8",
            "currency" => "$34.55",
            "alphanumeric" => "NSO74XND2HS"
        ],
        [
            "name" => "Candace Hansen",
            "phone" => "(850) 126-8561",
            "email" => "cubilia.curae.phasellus@hotmail.ca",
            "address" => "P.O. Box 818, 2344 Morbi Av.",
            "list" => "7",
            "country" => "Vietnam",
            "region" => "Bauchi",
            "postalZip" => "4392",
            "text" => "auctor, velit eget laoreet posuere, enim nisl elementum purus, accumsan",
            "numberrange" => "10",
            "currency" => "$13.67",
            "alphanumeric" => "CSC91PAS1XU"
        ],
        [
            "name" => "Charity Nash",
            "phone" => "(836) 668-0763",
            "email" => "et.libero@icloud.ca",
            "address" => "6693 Nunc Rd.",
            "list" => "17",
            "country" => "Philippines",
            "region" => "Niedersachsen",
            "postalZip" => "74215",
            "text" => "metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh.",
            "numberrange" => "7",
            "currency" => "$85.53",
            "alphanumeric" => "LAZ07MQX6YZ"
        ],
        [
            "name" => "Clark Vance",
            "phone" => "(627) 828-1711",
            "email" => "molestie@aol.edu",
            "address" => "P.O. Box 613, 6753 Eget, Rd.",
            "list" => "5",
            "country" => "United States",
            "region" => "Jigawa",
            "postalZip" => "21610",
            "text" => "tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque",
            "numberrange" => "1",
            "currency" => "$52.70",
            "alphanumeric" => "CRZ88FNJ8ID"
        ],
        [
            "name" => "Anika Stevenson",
            "phone" => "(575) 791-1751",
            "email" => "in.condimentum@icloud.ca",
            "address" => "Ap #781-6974 Parturient Av.",
            "list" => "17",
            "country" => "Belgium",
            "region" => "Chandigarh",
            "postalZip" => "816183",
            "text" => "tellus id nunc interdum feugiat. Sed nec metus facilisis lorem",
            "numberrange" => "10",
            "currency" => "$74.61",
            "alphanumeric" => "RUP12EZH7LE"
        ],
        [
            "name" => "Penelope Joseph",
            "phone" => "1-357-999-6828",
            "email" => "nec.euismod@protonmail.edu",
            "address" => "P.O. Box 625, 6684 Lorem St.",
            "list" => "17",
            "country" => "Italy",
            "region" => "Bahia",
            "postalZip" => "10431",
            "text" => "tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget",
            "numberrange" => "2",
            "currency" => "$0.68",
            "alphanumeric" => "YVP33YGU6MX"
        ],
        [
            "name" => "Yael Price",
            "phone" => "1-816-812-8084",
            "email" => "aenean.sed@icloud.couk",
            "address" => "451-3730 Mauris Road",
            "list" => "7",
            "country" => "Australia",
            "region" => "Tarapacá",
            "postalZip" => "532810",
            "text" => "eget, dictum placerat, augue. Sed molestie. Sed id risus quis",
            "numberrange" => "7",
            "currency" => "$97.36",
            "alphanumeric" => "QMX26FWG7GM"
        ],
        [
            "name" => "Eugenia Price",
            "phone" => "(883) 823-6155",
            "email" => "placerat.velit@yahoo.ca",
            "address" => "818-4480 Nulla Street",
            "list" => "9",
            "country" => "Norway",
            "region" => "La Guajira",
            "postalZip" => "35517",
            "text" => "id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus",
            "numberrange" => "3",
            "currency" => "$10.75",
            "alphanumeric" => "ESB85QQL6MW"
        ],
        [
            "name" => "Lareina Forbes",
            "phone" => "(481) 512-8928",
            "email" => "placerat.cras@hotmail.net",
            "address" => "P.O. Box 653, 1109 Enim, Ave",
            "list" => "11",
            "country" => "Norway",
            "region" => "Bayern",
            "postalZip" => "85169",
            "text" => "augue porttitor interdum. Sed auctor odio a purus. Duis elementum,",
            "numberrange" => "7",
            "currency" => "$94.49",
            "alphanumeric" => "HZN02LNR2NE"
        ],
        [
            "name" => "Risa Burnett",
            "phone" => "(527) 333-1446",
            "email" => "diam.vel.arcu@hotmail.edu",
            "address" => "Ap #960-8547 Nulla Ave",
            "list" => "7",
            "country" => "South Korea",
            "region" => "Ancash",
            "postalZip" => "233642",
            "text" => "ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna.",
            "numberrange" => "6",
            "currency" => "$70.97",
            "alphanumeric" => "UIK57HUL8LQ"
        ],
        [
            "name" => "Shana Reyes",
            "phone" => "1-775-752-2516",
            "email" => "blandit.nam.nulla@hotmail.couk",
            "address" => "Ap #898-5487 Enim Avenue",
            "list" => "9",
            "country" => "Singapore",
            "region" => "Zhōngnán",
            "postalZip" => "682152",
            "text" => "rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin",
            "numberrange" => "9",
            "currency" => "$66.89",
            "alphanumeric" => "SCW66BON7IX"
        ],
        [
            "name" => "Vladimir Pittman",
            "phone" => "(656) 831-8078",
            "email" => "metus.eu@icloud.edu",
            "address" => "P.O. Box 945, 5313 Semper, Street",
            "list" => "19",
            "country" => "Brazil",
            "region" => "Xīnán",
            "postalZip" => "376825",
            "text" => "cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet",
            "numberrange" => "6",
            "currency" => "$97.86",
            "alphanumeric" => "CRW52ESV5KO"
        ],
        [
            "name" => "Yetta Gonzales",
            "phone" => "1-587-608-0551",
            "email" => "enim@yahoo.ca",
            "address" => "Ap #378-4964 Tempus St.",
            "list" => "9",
            "country" => "Mexico",
            "region" => "Ceuta",
            "postalZip" => "817756",
            "text" => "vel arcu eu odio tristique pharetra. Quisque ac libero nec",
            "numberrange" => "1",
            "currency" => "$47.86",
            "alphanumeric" => "MVR66TTK5SO"
        ],
        [
            "name" => "Valentine Ward",
            "phone" => "1-403-617-3281",
            "email" => "odio.etiam@protonmail.edu",
            "address" => "973-4309 Felis. St.",
            "list" => "9",
            "country" => "Norway",
            "region" => "Drenthe",
            "postalZip" => "2814",
            "text" => "vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem ipsum dolor",
            "numberrange" => "0",
            "currency" => "$97.16",
            "alphanumeric" => "DTN27HZA8MH"
        ],
        [
            "name" => "Deacon Silva",
            "phone" => "1-530-840-2144",
            "email" => "amet@google.edu",
            "address" => "483-6599 Malesuada. Rd.",
            "list" => "17",
            "country" => "New Zealand",
            "region" => "Oklahoma",
            "postalZip" => "498518",
            "text" => "ante. Vivamus non lorem vitae odio sagittis semper. Nam tempor",
            "numberrange" => "1",
            "currency" => "$98.18",
            "alphanumeric" => "VXP35NUN3SE"
        ],
        [
            "name" => "Anjolie Poole",
            "phone" => "(357) 268-3664",
            "email" => "adipiscing.fringilla@protonmail.com",
            "address" => "P.O. Box 810, 146 Diam. St.",
            "list" => "19",
            "country" => "Philippines",
            "region" => "Drenthe",
            "postalZip" => "416477",
            "text" => "pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu",
            "numberrange" => "8",
            "currency" => "$25.14",
            "alphanumeric" => "CMM27QDP2SE"
        ],
        [
            "name" => "Violet Buchanan",
            "phone" => "1-164-353-7004",
            "email" => "in.aliquet@aol.net",
            "address" => "Ap #718-1759 Nonummy Street",
            "list" => "19",
            "country" => "Indonesia",
            "region" => "Atlántico",
            "postalZip" => "977976",
            "text" => "tellus non magna. Nam ligula elit, pretium et, rutrum non,",
            "numberrange" => "6",
            "currency" => "$90.69",
            "alphanumeric" => "UEM21KCW7OE"
        ],
        [
            "name" => "Tad Allen",
            "phone" => "(381) 647-6308",
            "email" => "ullamcorper@protonmail.ca",
            "address" => "Ap #912-8730 Eu St.",
            "list" => "5",
            "country" => "Indonesia",
            "region" => "Sumy oblast",
            "postalZip" => "2228",
            "text" => "vitae risus. Duis a mi fringilla mi lacinia mattis. Integer",
            "numberrange" => "5",
            "currency" => "$37.65",
            "alphanumeric" => "VKV00ZPD7ES"
        ],
        [
            "name" => "Cole Burnett",
            "phone" => "(319) 493-3661",
            "email" => "sed.sem.egestas@yahoo.org",
            "address" => "209-8436 Mauris Rd.",
            "list" => "11",
            "country" => "Canada",
            "region" => "Pernambuco",
            "postalZip" => "42712",
            "text" => "tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at",
            "numberrange" => "6",
            "currency" => "$98.20",
            "alphanumeric" => "TFG66ILN5FP"
        ],
        [
            "name" => "Heather Phillips",
            "phone" => "1-530-238-5723",
            "email" => "suspendisse.eleifend@aol.edu",
            "address" => "Ap #706-7773 Sodales Road",
            "list" => "7",
            "country" => "Philippines",
            "region" => "Vĩnh Long",
            "postalZip" => "2778",
            "text" => "Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit,",
            "numberrange" => "2",
            "currency" => "$90.17",
            "alphanumeric" => "WXU87FPJ7BN"
        ],
        [
            "name" => "Neville Buck",
            "phone" => "(712) 198-7244",
            "email" => "egestas@hotmail.com",
            "address" => "Ap #774-252 A, Road",
            "list" => "7",
            "country" => "Ukraine",
            "region" => "Heredia",
            "postalZip" => "573309",
            "text" => "ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper",
            "numberrange" => "2",
            "currency" => "$37.78",
            "alphanumeric" => "RXR42UHS1ZK"
        ],
        [
            "name" => "Murphy Meyer",
            "phone" => "(236) 733-9020",
            "email" => "pede.malesuada@outlook.com",
            "address" => "P.O. Box 227, 5181 Ac St.",
            "list" => "13",
            "country" => "Chile",
            "region" => "North Jeolla",
            "postalZip" => "33408",
            "text" => "ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris",
            "numberrange" => "6",
            "currency" => "$26.88",
            "alphanumeric" => "PDV46NHC1BJ"
        ],
        [
            "name" => "Jackson James",
            "phone" => "(842) 258-2324",
            "email" => "fringilla.est.mauris@protonmail.ca",
            "address" => "P.O. Box 149, 6771 Nulla. Av.",
            "list" => "19",
            "country" => "South Korea",
            "region" => "Pará",
            "postalZip" => "3726",
            "text" => "Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros.",
            "numberrange" => "1",
            "currency" => "$33.47",
            "alphanumeric" => "ELX47VNV8CW"
        ],
        [
            "name" => "Berk Case",
            "phone" => "(444) 265-4787",
            "email" => "ligula@hotmail.edu",
            "address" => "4749 Adipiscing Street",
            "list" => "13",
            "country" => "India",
            "region" => "Cao Bằng",
            "postalZip" => "17102",
            "text" => "vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat",
            "numberrange" => "6",
            "currency" => "$13.97",
            "alphanumeric" => "SRD42ZUK7HR"
        ],
        [
            "name" => "Cadman Harrison",
            "phone" => "(306) 963-6435",
            "email" => "nulla.vulputate@icloud.ca",
            "address" => "126-7361 Tellus Rd.",
            "list" => "15",
            "country" => "Costa Rica",
            "region" => "North Island",
            "postalZip" => "7745",
            "text" => "facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant",
            "numberrange" => "4",
            "currency" => "$49.56",
            "alphanumeric" => "KQI94JKV6NZ"
        ],
        [
            "name" => "Tanek Shannon",
            "phone" => "(111) 642-9828",
            "email" => "primis.in@icloud.edu",
            "address" => "Ap #873-389 Curae Street",
            "list" => "3",
            "country" => "India",
            "region" => "Huáběi",
            "postalZip" => "11213",
            "text" => "elementum, dui quis accumsan convallis, ante lectus convallis est, vitae",
            "numberrange" => "2",
            "currency" => "$51.13",
            "alphanumeric" => "NKR76DNO4JU"
        ],
        [
            "name" => "Adam Lopez",
            "phone" => "(601) 148-9310",
            "email" => "id@yahoo.ca",
            "address" => "Ap #155-9996 Nec Rd.",
            "list" => "13",
            "country" => "Spain",
            "region" => "Heredia",
            "postalZip" => "4571",
            "text" => "fringilla cursus purus. Nullam scelerisque neque sed sem egestas blandit.",
            "numberrange" => "4",
            "currency" => "$62.94",
            "alphanumeric" => "RNG98VNC0FL"
        ],
        [
            "name" => "Thomas Rodriquez",
            "phone" => "(583) 659-7316",
            "email" => "vulputate.ullamcorper.magna@icloud.ca",
            "address" => "455-4838 Vulputate, St.",
            "list" => "3",
            "country" => "Italy",
            "region" => "Junín",
            "postalZip" => "3725-8798",
            "text" => "eu augue porttitor interdum. Sed auctor odio a purus. Duis",
            "numberrange" => "7",
            "currency" => "$95.89",
            "alphanumeric" => "CQO64VHV8VQ"
        ],
        [
            "name" => "Jenette Holder",
            "phone" => "(513) 663-1885",
            "email" => "ac.mi.eleifend@aol.edu",
            "address" => "P.O. Box 137, 9621 Eu St.",
            "list" => "19",
            "country" => "Costa Rica",
            "region" => "South Island",
            "postalZip" => "03932-00442",
            "text" => "non enim commodo hendrerit. Donec porttitor tellus non magna. Nam",
            "numberrange" => "5",
            "currency" => "$62.60",
            "alphanumeric" => "JZJ18HDO9UU"
        ],
        [
            "name" => "Cynthia Espinoza",
            "phone" => "1-243-518-8583",
            "email" => "metus.vivamus.euismod@icloud.edu",
            "address" => "Ap #952-2078 Mauris Rd.",
            "list" => "19",
            "country" => "Costa Rica",
            "region" => "Viken",
            "postalZip" => "628782",
            "text" => "lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante",
            "numberrange" => "2",
            "currency" => "$24.49",
            "alphanumeric" => "LJD69BBV3MG"
        ],
        [
            "name" => "Abbot England",
            "phone" => "1-862-443-1582",
            "email" => "posuere@aol.com",
            "address" => "582-7211 Tempus Road",
            "list" => "1",
            "country" => "Colombia",
            "region" => "Free State",
            "postalZip" => "554528",
            "text" => "sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue",
            "numberrange" => "8",
            "currency" => "$70.40",
            "alphanumeric" => "TGE76NXV5NQ"
        ],
        [
            "name" => "Scott Salinas",
            "phone" => "(218) 461-1342",
            "email" => "rutrum.non@yahoo.org",
            "address" => "555-2800 Quam Ave",
            "list" => "7",
            "country" => "Italy",
            "region" => "Khyber Pakhtoonkhwa",
            "postalZip" => "5663",
            "text" => "quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam",
            "numberrange" => "1",
            "currency" => "$36.93",
            "alphanumeric" => "EVL54PIU6KL"
        ],
        [
            "name" => "Sebastian Garrison",
            "phone" => "(231) 315-9353",
            "email" => "nunc@icloud.com",
            "address" => "P.O. Box 963, 9712 Rutrum Road",
            "list" => "9",
            "country" => "China",
            "region" => "Dalarnas län",
            "postalZip" => "8662",
            "text" => "tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim",
            "numberrange" => "6",
            "currency" => "$0.34",
            "alphanumeric" => "SIX27TQY6CS"
        ],
        [
            "name" => "Aaron Dejesus",
            "phone" => "(235) 434-8134",
            "email" => "viverra.donec@icloud.com",
            "address" => "154-4541 Convallis Ave",
            "list" => "7",
            "country" => "Chile",
            "region" => "Styria",
            "postalZip" => "498496",
            "text" => "ornare. Fusce mollis. Duis sit amet diam eu dolor egestas",
            "numberrange" => "7",
            "currency" => "$54.23",
            "alphanumeric" => "BVD82NFM5OO"
        ],
        [
            "name" => "Griffith Osborn",
            "phone" => "(794) 524-3420",
            "email" => "integer.id@google.ca",
            "address" => "7487 Turpis. Av.",
            "list" => "19",
            "country" => "Brazil",
            "region" => "Balochistan",
            "postalZip" => "8355 GD",
            "text" => "Sed id risus quis diam luctus lobortis. Class aptent taciti",
            "numberrange" => "4",
            "currency" => "$83.37",
            "alphanumeric" => "GXR75BNX2VH"
        ]
    );

    public function retornarDados($campo, $valor){ 
        if(empty($campo) && empty($valor)){
            return($this->entrada);
        }
        else{
            $i=sizeof(($this->entrada));
            while($i > 0){
                $i--;
                if(str_contains($this->entrada[$i][$campo], $valor)){
                    return([$this->entrada[$i]]);
                }               
            }

        }
    }
};
?>